site: Nicholas Eager

url: https://nicholaseager.com
baseurl: 

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  places:
    output: true
    permalink: /place/:slug
  themes:
    output: true
    permalink: /theme/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "places"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "themes"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 10
paginate_path: "/blog/page:num/"

grid_alignments:
  - top
  - center
  - bottom