site: Nicholas Eager

url: https://nicholaseager.com
baseurl: 

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  guides:
    output: true
    permalink: /guides/:slug
  photos:
    output: true
    permalink: :path
  galleries:
    output: true
    permalink: /galleries/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

author:
  name: Nicholas Eager
  image: https://ik.imagekit.io/qn1gkawvy/tr:w-1280/profile.jpg
  url: https://nicholaseager.com/about
  description: Nicholas Eager is an international adventure filmmaker and photographer.
twitter:
  username: eager_photo
  card: summary_large_image
social:
  name: Nicholas Eager
  links:
    - https://www.instagram.com/nicholas.eager/
    - https://www.youtube.com/c/NicholasEager
    - https://www.facebook.com/nicholas.eager.photo

organization:
  name: Nicholas Eager Photography
  image: https://ik.imagekit.io/qn1gkawvy/tr:w-1280/profile.jpg
  copyright: Nicholas Eager Photography, LLC

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

paginate: 10
paginate_path: "/blog/page:num/"

grid_alignments:
  - top
  - center
  - bottom