basic_settings:
  site_title: Nicholas Eager
  favicon_image: /images/favicon.png

menu_settings:
  menu_items:
    - title: 'Photos'
      url: '/photos'
    - title: 'Guides'
      url: '/guides'
    - title: 'Gear'
      url: '/gear'
    - title: 'Blog'
      url: '/blog/'
    - title: 'About'
      url: '/about'
    - title: 'Contact'
      url: '/contact'
  footer_items:
    - title: Privacy
      url: /privacy-policy
    - title: Terms
      url: /terms-and-conditions
    - title: Licensing
      url: /how-to-use-my-art

footer_settings:
  footer_tagline: Nicholas Eager Photography

contact_settings:
  form_action: 'https://formspree.io/f/mvolakjj'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: 'https://www.facebook.com/nicholas.eager.photo'
  twitter_url: ''
  instagram_url: 'https://www.instagram.com/nicholas.eager/'
  snapchat_url: ''
  youtube_url: 'https://www.youtube.com/channel/UCv-z2Q0Ucx8lxq8mvYRK28g'
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''
  500px_url: ''
  strava_url: ''

